version: '3.4'

services:
  movements-db:
    container_name: movements-db
    image: mongo
    command: mongod --port 27016
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: user-movements
    ports:
      - 27016:27016
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend

  movements-server:
    container_name: movements-server
    build:
      context: '.'
    env_file:
      - ./.env
    command: "npm run start:dev"
    restart: always
    depends_on:
      - movements-db
    ports:
      - 3000:7070
    volumes:
      - './src:/app/src'
    links: 
      - movements-db
    networks:
      - backend

volumes:
  movements-db-volume-data:
  movements-db-volume-logs:

networks:
  backend:
    driver: bridge