version: '3.4'

services:
  movements-db:
    container_name: movements-db
    image: mongo
    command: mongod --port 27016
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27016:27016
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bynder.io

  movements-server:
    container_name: movements-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    command: "npm run start:prod"
    restart: always
    depends_on:
      - movements-db
    ports:
      - 3000:7070
    volumes:
      - ./src:/usr/app/
    links: 
      - movements-db
    networks:
      - bynder.io

volumes:
  movements-db-volume-data:
  movements-db-volume-logs:

networks:
  bynder.io:
    driver: bridge
